-- prepares user country data for student annotators
with distinct_locations as (select distinct trim(lower(location)) as location from {{ production_dataset }}.repo_owners)

select

  location,
  "hard" as difficulty

from
  distinct_locations
where
  not regexp_contains(
    location,
    r"(?i)(Abkhazia)|(Afghanistan)|(Albania)|(Algeria)|(Andorra)|(Angola)|(Antigua and Barbuda)|(Argentina)|(Armenia)|(Australia)|(Austria)|(Azerbaijan)|(Bahrain)|(Bangladesh)|(Barbados)|(Belarus)|(Belgium)|(Belize)|(Benin)|(Bhutan)|(Bolivia)|(Bosnia and Herzegovina)|(Botswana)|(Brazil)|(Brunei)|(Bulgaria)|(Burkina Faso)|(Burundi)|(Cambodia)|(Cameroon)|(Canada)|(Cape Verde)|(Central African Republic)|(Chad)|(Chile)|(China)|(Colombia)|(Comoros)|(Congo)|(Costa Rica)|(Croatia)|(Cuba)|(Cyprus)|(Czech Republic)|(Côte d'Ivoire)|(Democratic Republic of Congo)|(Denmark)|(Djibouti)|(Dominica)|(Dominican Republic)|(East Timor)|(Ecuador)|(Egypt)|(El Salvador)|(Equatorial Guinea)|(Eritrea)|(Estonia)|(Eswatini)|(Ethiopia)|(Fiji)|(Finland)|(France)|(Gabon)|(Gambia)|(Georgia)|(Germany)|(Ghana)|(Greece)|(Grenada)|(Guatemala)|(Guinea)|(Guinea-Bissau)|(Guyana)|(Haiti)|(Honduras)|(Hungary)|(Iceland)|(India)|(Indonesia)|(Iran)|(Iraq)|(Ireland)|(Israel)|(Italy)|(Jamaica)|(Japan)|(Jordan)|(Kazakhstan)|(Kenya)|(Kiribati)|(Kosovo)|(Kuwait)|(Kyrgyzstan)|(Laos)|(Latvia)|(Lebanon)|(Lesotho)|(Liberia)|(Libya)|(Liechtenstein)|(Lithuania)|(Luxembourg)|(Madagascar)|(Malawi)|(Malaysia)|(Maldives)|(Mali)|(Malta)|(Marshall Islands)|(Mauritania)|(Mauritius)|(Mexico)|(Micronesia)|(Moldova)|(Monaco)|(Mongolia)|(Montenegro)|(Morocco)|(Mozambique)|(Myanmar)|(Namibia)|(Nauru)|(Nepal)|(Netherlands)|(New Zealand)|(Nicaragua)|(Niger)|(Nigeria)|(North Korea)|(North Macedonia)|(Norway)|(Oman)|(Pakistan)|(Palau)|(Palestine)|(Panama)|(Papua New Guinea)|(Paraguay)|(Peru)|(Philippines)|(Poland)|(Portugal)|(Puerto Rico)|(Qatar)|(Romania)|(Russia)|(Rwanda)|(Saint Kitts and Nevis)|(Saint Lucia)|(Saint Vincent and the Grenadines)|(Samoa)|(San Marino)|(Saudi Arabia)|(Senegal)|(Serbia)|(Seychelles)|(Sierra Leone)|(Singapore)|(Slovakia)|(Slovenia)|(Solomon Islands)|(Somalia)|(South Africa)|(South Korea)|(South Sudan)|(Spain)|(Sri Lanka)|(Sudan)|(Suriname)|(Sweden)|(Switzerland)|(Syria)|(São Tomé and Príncipe)|(Taiwan)|(Tajikistan)|(Tanzania)|(Thailand)|(The Bahamas)|(Togo)|(Tonga)|(Transnistria)|(Trinidad and Tobago)|(Tunisia)|(Turkey)|(Turkmenistan)|(Tuvalu)|(Uganda)|(Ukraine)|(United Arab Emirates)|(United Kingdom)|(United States)|(Uruguay)|(Uzbekistan)|(Vanuatu)|(Vatican City)|(Venezuela)|(Vietnam)|(Western Sahara)|(Yemen)|(Zambia)|(Zimbabwe)" -- noqa: L016
  ) and not location like "%http%"
union all
(
  select
    location,
    "easy" as difficulty
  from
    distinct_locations
  where
    regexp_contains(
      location,
      r"(?i)(Abkhazia)|(Afghanistan)|(Albania)|(Algeria)|(Andorra)|(Angola)|(Antigua and Barbuda)|(Argentina)|(Armenia)|(Australia)|(Austria)|(Azerbaijan)|(Bahrain)|(Bangladesh)|(Barbados)|(Belarus)|(Belgium)|(Belize)|(Benin)|(Bhutan)|(Bolivia)|(Bosnia and Herzegovina)|(Botswana)|(Brazil)|(Brunei)|(Bulgaria)|(Burkina Faso)|(Burundi)|(Cambodia)|(Cameroon)|(Canada)|(Cape Verde)|(Central African Republic)|(Chad)|(Chile)|(China)|(Colombia)|(Comoros)|(Congo)|(Costa Rica)|(Croatia)|(Cuba)|(Cyprus)|(Czech Republic)|(Côte d'Ivoire)|(Democratic Republic of Congo)|(Denmark)|(Djibouti)|(Dominica)|(Dominican Republic)|(East Timor)|(Ecuador)|(Egypt)|(El Salvador)|(Equatorial Guinea)|(Eritrea)|(Estonia)|(Eswatini)|(Ethiopia)|(Fiji)|(Finland)|(France)|(Gabon)|(Gambia)|(Georgia)|(Germany)|(Ghana)|(Greece)|(Grenada)|(Guatemala)|(Guinea)|(Guinea-Bissau)|(Guyana)|(Haiti)|(Honduras)|(Hungary)|(Iceland)|(India)|(Indonesia)|(Iran)|(Iraq)|(Ireland)|(Israel)|(Italy)|(Jamaica)|(Japan)|(Jordan)|(Kazakhstan)|(Kenya)|(Kiribati)|(Kosovo)|(Kuwait)|(Kyrgyzstan)|(Laos)|(Latvia)|(Lebanon)|(Lesotho)|(Liberia)|(Libya)|(Liechtenstein)|(Lithuania)|(Luxembourg)|(Madagascar)|(Malawi)|(Malaysia)|(Maldives)|(Mali)|(Malta)|(Marshall Islands)|(Mauritania)|(Mauritius)|(Mexico)|(Micronesia)|(Moldova)|(Monaco)|(Mongolia)|(Montenegro)|(Morocco)|(Mozambique)|(Myanmar)|(Namibia)|(Nauru)|(Nepal)|(Netherlands)|(New Zealand)|(Nicaragua)|(Niger)|(Nigeria)|(North Korea)|(North Macedonia)|(Norway)|(Oman)|(Pakistan)|(Palau)|(Palestine)|(Panama)|(Papua New Guinea)|(Paraguay)|(Peru)|(Philippines)|(Poland)|(Portugal)|(Puerto Rico)|(Qatar)|(Romania)|(Russia)|(Rwanda)|(Saint Kitts and Nevis)|(Saint Lucia)|(Saint Vincent and the Grenadines)|(Samoa)|(San Marino)|(Saudi Arabia)|(Senegal)|(Serbia)|(Seychelles)|(Sierra Leone)|(Singapore)|(Slovakia)|(Slovenia)|(Solomon Islands)|(Somalia)|(South Africa)|(South Korea)|(South Sudan)|(Spain)|(Sri Lanka)|(Sudan)|(Suriname)|(Sweden)|(Switzerland)|(Syria)|(São Tomé and Príncipe)|(Taiwan)|(Tajikistan)|(Tanzania)|(Thailand)|(The Bahamas)|(Togo)|(Tonga)|(Transnistria)|(Trinidad and Tobago)|(Tunisia)|(Turkey)|(Turkmenistan)|(Tuvalu)|(Uganda)|(Ukraine)|(United Arab Emirates)|(United Kingdom)|(United States)|(Uruguay)|(Uzbekistan)|(Vanuatu)|(Vatican City)|(Venezuela)|(Vietnam)|(Western Sahara)|(Yemen)|(Zambia)|(Zimbabwe)" -- noqa: L016
    ) and (not location like "%http%") and not regexp_contains(
      location,
      r"(?i)^\s*((Abkhazia)|(Afghanistan)|(Albania)|(Algeria)|(Andorra)|(Angola)|(Antigua and Barbuda)|(Argentina)|(Armenia)|(Australia)|(Austria)|(Azerbaijan)|(Bahrain)|(Bangladesh)|(Barbados)|(Belarus)|(Belgium)|(Belize)|(Benin)|(Bhutan)|(Bolivia)|(Bosnia and Herzegovina)|(Botswana)|(Brazil)|(Brunei)|(Bulgaria)|(Burkina Faso)|(Burundi)|(Cambodia)|(Cameroon)|(Canada)|(Cape Verde)|(Central African Republic)|(Chad)|(Chile)|(China)|(Colombia)|(Comoros)|(Congo)|(Costa Rica)|(Croatia)|(Cuba)|(Cyprus)|(Czech Republic)|(Côte d'Ivoire)|(Democratic Republic of Congo)|(Denmark)|(Djibouti)|(Dominica)|(Dominican Republic)|(East Timor)|(Ecuador)|(Egypt)|(El Salvador)|(Equatorial Guinea)|(Eritrea)|(Estonia)|(Eswatini)|(Ethiopia)|(Fiji)|(Finland)|(France)|(Gabon)|(Gambia)|(Georgia)|(Germany)|(Ghana)|(Greece)|(Grenada)|(Guatemala)|(Guinea)|(Guinea-Bissau)|(Guyana)|(Haiti)|(Honduras)|(Hungary)|(Iceland)|(India)|(Indonesia)|(Iran)|(Iraq)|(Ireland)|(Israel)|(Italy)|(Jamaica)|(Japan)|(Jordan)|(Kazakhstan)|(Kenya)|(Kiribati)|(Kosovo)|(Kuwait)|(Kyrgyzstan)|(Laos)|(Latvia)|(Lebanon)|(Lesotho)|(Liberia)|(Libya)|(Liechtenstein)|(Lithuania)|(Luxembourg)|(Madagascar)|(Malawi)|(Malaysia)|(Maldives)|(Mali)|(Malta)|(Marshall Islands)|(Mauritania)|(Mauritius)|(Mexico)|(Micronesia)|(Moldova)|(Monaco)|(Mongolia)|(Montenegro)|(Morocco)|(Mozambique)|(Myanmar)|(Namibia)|(Nauru)|(Nepal)|(Netherlands)|(New Zealand)|(Nicaragua)|(Niger)|(Nigeria)|(North Korea)|(North Macedonia)|(Norway)|(Oman)|(Pakistan)|(Palau)|(Palestine)|(Panama)|(Papua New Guinea)|(Paraguay)|(Peru)|(Philippines)|(Poland)|(Portugal)|(Puerto Rico)|(Qatar)|(Romania)|(Russia)|(Rwanda)|(Saint Kitts and Nevis)|(Saint Lucia)|(Saint Vincent and the Grenadines)|(Samoa)|(San Marino)|(Saudi Arabia)|(Senegal)|(Serbia)|(Seychelles)|(Sierra Leone)|(Singapore)|(Slovakia)|(Slovenia)|(Solomon Islands)|(Somalia)|(South Africa)|(South Korea)|(South Sudan)|(Spain)|(Sri Lanka)|(Sudan)|(Suriname)|(Sweden)|(Switzerland)|(Syria)|(São Tomé and Príncipe)|(Taiwan)|(Tajikistan)|(Tanzania)|(Thailand)|(The Bahamas)|(Togo)|(Tonga)|(Transnistria)|(Trinidad and Tobago)|(Tunisia)|(Turkey)|(Turkmenistan)|(Tuvalu)|(Uganda)|(Ukraine)|(United Arab Emirates)|(United Kingdom)|(United States)|(Uruguay)|(Uzbekistan)|(Vanuatu)|(Vatican City)|(Venezuela)|(Vietnam)|(Western Sahara)|(Yemen)|(Zambia)|(Zimbabwe))\s*$" -- noqa: L016
    )
  limit 1060
)
